// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Guide is the WikiService.Guide payload. Rel/origin/kind come from Locate.
 */
export interface Guide {
    "rel": string;
    "origin": string;
    "originName": string;
    "kind": string;
    "pages": GuidePage[] | null;
    "attribution": string;
}

/**
 * GuidePage is one tab in the Guide pane.
 */
export interface GuidePage {
    "title": string;
    "html": string;
    "url": string;
    "snippets": string[] | null;
    "sections": Section[] | null;
}

/**
 * PatchEntry is one row in the Patch Notes version tree.
 */
export interface PatchEntry {
    "title": string;
    "version": string;
    "parent": string;
    "url": string;
    "hasModding": boolean;
}

/**
 * PatchList is the WikiService.Patches payload.
 */
export interface PatchList {
    "gameId": string;
    "pages": PatchEntry[] | null;
}

/**
 * PatchPage is one patch notes body (All + optional Modding HTML).
 */
export interface PatchPage {
    "title": string;
    "version": string;
    "html": string;
    "moddingHtml": string;
    "url": string;
    "hasModding": boolean;
    "sections": Section[] | null;
    "moddingSections": Section[] | null;
}

/**
 * Section is one MediaWiki TOC entry kept for heading extraction.
 */
export interface Section {
    "tocLevel": number;
    "line": string;
    "anchor": string;
}

/**
 * Status is the WikiService.Status payload.
 */
export interface Status {
    "gameId": string;
    "present": boolean;
    "fetchedAt": string;
    "fetchedVersion": string;
    "fetchedMajor": number;
    "fetchedMinor": number;
    "guideCount": number;
    "patchCount": number;
}
