// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as schemaeval$0 from "../schemaeval/models.js";

/**
 * Cache is the generated install semantic model (JSON in user-data).
 */
export interface Cache {
    "gameId": string;
    "installPath": string;
    "scannedAt": string;
    "schemas": { [_ in string]?: schemaeval$0.Schema } | null;
    "defKeys": { [_ in string]?: string[] | null } | null;
    "guiTypes": string[] | null;
    "guiProps": string[] | null;
    "locKeyCount": { [_ in string]?: number } | null;
    "effects"?: string[] | null;
    "triggers"?: string[] | null;
}
