// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Cache is the vanilla semantic model for one (game, version). It is derived
 * entirely from the install and reused across every workspace on that version.
 * All string slices are sorted, de-duplicated membership sets (no frequencies).
 */
export interface Cache {
    "formatVersion": number;
    "gameId": string;
    "installPath": string;
    "gameVersion": string;
    "scannedAt": string;

    /**
     * Defs are the vanilla object definitions (script kinds; not loc keys).
     */
    "defs": Def[] | null;

    /**
     * LocEnglish maps every english loc key to its (length-capped) value.
     */
    "locEnglish": { [_ in string]?: string } | null;

    /**
     * FieldDocs maps a field/token key to human doc prose from shipped docs or
     * a script_docs dump.
     */
    "fieldDocs": { [_ in string]?: string } | null;

    /**
     * Structures maps a definition kind to the set of keys valid as its direct
     * children (union of documented keys and keys observed in the corpus).
     */
    "structures": { [_ in string]?: string[] | null } | null;

    /**
     * Vocabulary is the corpus baseline: every script key observed inside
     * definition bodies. Always populated, even with no script_docs dump.
     */
    "vocabulary": string[] | null;

    /**
     * Effects/Triggers/Modifiers are classified by a script_docs dump when one is
     * present; otherwise empty and callers fall back to Vocabulary.
     */
    "effects": string[] | null;
    "triggers": string[] | null;
    "modifiers": string[] | null;

    /**
     * Objects are the referable definition names (every Def.Key).
     */
    "objects": string[] | null;

    /**
     * GUITypes / GUIProps are the widget type names and property keys from .gui.
     */
    "guiTypes": string[] | null;
    "guiProps": string[] | null;

    /**
     * MetaKeys are the top-level keys seen in .metadata/metadata.json files.
     */
    "metaKeys": string[] | null;

    /**
     * RootScopes maps a definition kind to the scope its body runs in, when the
     * shipped docs declared it (e.g. "scripted_effect" is scopeless -> absent).
     */
    "rootScopes"?: { [_ in string]?: string } | null;
}

/**
 * Def is one definition: a named object the game (or a mod) declares. Path is the
 * absolute file it lives in; Line is 0-based. Type is the definition kind as
 * classified by game.MatchExtract (e.g. "trait", "event", "scripted_effect").
 * Origin is the mod id that declared it, or "" for vanilla.
 */
export interface Def {
    "type": string;
    "key": string;
    "path": string;
    "line": number;
    "origin"?: string;
}

/**
 * OverrideRow is one contested key: its kind/name, the resolution rule, the winning
 * origin, and every site that defines it.
 */
export interface OverrideRow {
    "kind": string;
    "name": string;

    /**
     * "FIOS" | "LIOS"
     */
    "rule": string;
    "winner": string;
    "sites": OverrideSite[] | null;
}

/**
 * OverrideSite is one place a key is defined, for the conflict monitor.
 */
export interface OverrideSite {
    /**
     * "" = vanilla
     */
    "origin": string;
    "file": string;
    "line": number;
}
