// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Def is one named object: Kind/Key, absolute Path, 0-based Line, Origin ("" = vanilla).
 * OwnerKey is the enclosing scripted macro for script_param defs.
 * Value is the harvested RHS literal at a ScriptName def site (hover body).
 */
export interface Def {
    "kind": string;
    "key": string;
    "path": string;
    "line": number;
    "start"?: number;
    "end"?: number;
    "origin"?: string;
    "ownerKey"?: string;
    "value"?: string;
}

/**
 * Edge is a directed event-graph link. Kind "call" is a scripted-effect invocation.
 */
export interface Edge {
    "from": string;
    "to": string;
    "via": string;
    "path": string;
    "line": number;
    "kind"?: string;
    "nameKey"?: string;
}

/**
 * Ref is a use-site. Kind is "loc", "loc-broad", "loc-convention",
 * "event", "on_action", or an ephemeral/script kind. OwnerKey scopes
 * script_param refs to the enclosing scripted_* call.
 */
export interface Ref {
    "key": string;
    "kind": string;
    "path": string;
    "line": number;
    "start": number;
    "end": number;
    "ownerKey"?: string;
}

/**
 * VanillaCache is the vanilla script model for one install + version.
 */
export interface VanillaCache {
    "formatVersion": number;
    "installId": string;
    "gameId": string;
    "installPath": string;
    "gameVersion": string;
    "scannedAt": string;
    "defs": Def[] | null;
    "fieldInfo": { [_ in string]?: string } | null;
    "fieldInfoByKind": { [_ in string]?: { [_ in string]?: string } | null } | null;
    "structures": { [_ in string]?: string[] | null } | null;
    "structureBlocks"?: { [_ in string]?: string[] | null } | null;
    "vocabulary": string[] | null;
    "effects": string[] | null;
    "triggers": string[] | null;
    "guiTypes": string[] | null;
    "guiProps": string[] | null;
    "metaKeys": string[] | null;
    "edges"?: Edge[] | null;
    "locRefs"?: Ref[] | null;

    /**
     * scripted_* call sites
     */
    "callRefs"?: Ref[] | null;
    "fieldValueKinds"?: { [_ in string]?: string } | null;
    "fieldEnumsByKind"?: { [_ in string]?: { [_ in string]?: string[] | null } | null } | null;
    "tokenUsage"?: { [_ in string]?: string } | null;
    "tokenDoc"?: { [_ in string]?: string } | null;
    "tokenScopes"?: { [_ in string]?: string } | null;
    "dataFunctions"?: string[] | null;
}
