// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Def is one named object: Kind/Key, absolute Path, 0-based Line, Origin ("" = vanilla).
 * OwnerKey is the enclosing scripted macro for script_param defs.
 * Value is the harvested RHS literal at a ScriptName def site (hover body).
 */
export interface Def {
    "kind": string;
    "key": string;
    "path": string;
    "line": number;
    "start"?: number;
    "end"?: number;
    "origin"?: string;
    "ownerKey"?: string;
    "value"?: string;

    /**
     * Doc is the comment block written immediately above the definition. For
     * most objects it is the only description that exists: script_docs covers
     * the engine API, not script, so no dump describes an event, a decision, a
     * trait or a scripted macro. Authors write a comment instead.
     */
    "doc"?: string;
}

/**
 * Edge is a directed event-graph link. Kind "call" is a scripted-effect invocation.
 */
export interface Edge {
    "from": string;
    "to": string;
    "via": string;
    "path": string;
    "line": number;
    "kind"?: string;
    "nameKey"?: string;
}

/**
 * EngineToken is one effect or trigger. In is Supported Scopes ("none" means
 * usable anywhere); Target is Supported Targets, the argument's scope type.
 */
export interface EngineToken {
    "in"?: string[] | null;
    "target"?: string;
    "doc"?: string;
    "usage"?: string;
}

/**
 * LocAffix is one derived localization naming convention for a kind: the key
 * for a definition of that kind is Pre + <def id> + Suf. Both halves may be
 * empty, which is the convention that a definition's key is simply its id.
 */
export interface LocAffix {
    "pre"?: string;
    "suf"?: string;

    /**
     * definitions of the kind that carry this key
     */
    "defs": number;

    /**
     * definitions of the kind in the install
     */
    "of": number;
}

/**
 * affixesFrom is the derivation itself: given names that belong to a kind, and
 * how many names each kind has, find the prefix/suffix shapes that turn enough
 * of them into real localization keys.
 * LocKeyAffix is a loc key shape derived from another loc key rather than from
 * a definition. EU5 writes NOT_<key> for the negated form of a trigger tooltip,
 * so NOT_POP_LITERACY_TRIGGER is consumed by the engine even though nothing
 * cites it and no definition is named POP_LITERACY_TRIGGER — the stem is
 * itself a key. Vanilla EU5 has 69,565 keys reading as orphaned and this family
 * is its largest cluster; see GAME-SYNTAX §12.
 */
export interface LocKeyAffix {
    "pre"?: string;
    "suf"?: string;

    /**
     * Keys carrying this shape whose stem is itself a loc key, out of Of, every
     * key carrying it. The ratio is the evidence: a real derivation resolves
     * nearly always, a coincidence resolves sometimes.
     */
    "keys": number;
    "of": number;
}

/**
 * Modifier is one modifier token. Area is CK3 "Use areas" / Vic3 "Mask".
 */
export interface Modifier {
    "name"?: string;
    "doc"?: string;
    "area"?: string;
}

/**
 * NestedShape is a derived parent→child harvest pattern (faiths under religion,
 * nested titles, law policies, …). GroupKey is the wrapper when every hit
 * sat under the same assignment.
 */
export interface NestedShape {
    "parentKind": string;
    "childKind": string;
    "groupKey"?: string;

    /**
     * KeyPrefix is the shared `X_` first letters of discovered child keys
     * (CK3 titles: "ekdcb"). Empty means harvest every matching block.
     */
    "keyPrefix"?: string;

    /**
     * SkipKeys marks an option database and lists the inner keys that are
     * ordinary fields rather than rows — a game rule's `categories` and
     * `default`. Everything else under the parent is a row, so a mod that adds
     * its own option is picked up without re-deriving anything.
     */
    "skipKeys"?: string[] | null;

    /**
     * IsOption distinguishes an option database with nothing to skip (every key
     * under the group is a row) from an ordinary cite-driven nested shape.
     */
    "isOption"?: boolean;
}

/**
 * Ref is a use-site. Kind is "loc", "loc-broad", "loc-convention",
 * "event", "on_action", or an ephemeral/script kind. OwnerKey scopes
 * script_param refs to the enclosing scripted_* call.
 */
export interface Ref {
    "key": string;
    "kind": string;
    "path": string;
    "line": number;
    "start": number;
    "end": number;
    "ownerKey"?: string;
}

/**
 * Schema is the declared type system for one install, read from script_docs.
 * Nil means the user has not run script_docs; callers degrade rather than guess.
 */
export interface Schema {
    "scopes"?: { [_ in string]?: ScopeType } | null;
    "links"?: { [_ in string]?: ScopeLink } | null;
    "effects"?: { [_ in string]?: EngineToken } | null;
    "triggers"?: { [_ in string]?: EngineToken } | null;
    "onActions"?: { [_ in string]?: string } | null;
    "modifiers"?: { [_ in string]?: Modifier } | null;

    /**
     * SavedScopes are the scope names the engine saves itself (actor, recipient,
     * …), listed under "Event Targets Saved from Code" in event_targets.log.
     */
    "savedScopes"?: string[] | null;

    /**
     * ScopesDerived says Scopes was recovered from the link table rather than
     * declared: only CK3 ships event_scopes.log. Provenance is kept because a
     * derived entry carries only ChangeScopes / EvaluateTriggers, never the
     * ExecuteEffects / StoresVariables / SaveToken facts no other file states.
     */
    "scopesDerived"?: boolean;

    /**
     * Source says whether the dumps came from the game's user-data folder or
     * from PMT's archived copy, so the UI can tell the user.
     */
    "source"?: SchemaSource;

    /**
     * ReadAt is the newest dump mtime (RFC3339), for staleness against the install.
     */
    "readAt"?: string;
}

/**
 * SchemaSource says where a Schema was read from.
 */
export enum SchemaSource {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * SchemaLive means the game's own user-data folder supplied the dumps.
     */
    SchemaLive = "live",

    /**
     * SchemaArchive means the live dumps were gone and PMT's copy was used.
     */
    SchemaArchive = "archive",

    /**
     * SchemaMissing means neither exists; the engine runs without a type system.
     */
    SchemaMissing = "missing",
};

/**
 * ScopeLink is one scope transition (event_targets.log). In is the scope types
 * the link may be used from; Out is the type it yields. Global+Data together
 * mean the link is cited as `name:key` — this is the typed-prefix table.
 */
export interface ScopeLink {
    "in"?: string[] | null;
    "out"?: string;
    "global"?: boolean;
    "data"?: boolean;
    "wild"?: boolean;
    "doc"?: string;
}

/**
 * ScopeType is one entry of the game's scope-type universe (event_scopes.log).
 * A scope type is the "class" an effect or trigger runs against.
 */
export interface ScopeType {
    "evaluateTriggers"?: boolean;
    "executeEffects"?: boolean;
    "changeScopes"?: boolean;
    "storesVariables"?: boolean;
    "saveToken"?: string;
}

/**
 * VanillaCache is the vanilla script model for one install + version.
 */
export interface VanillaCache {
    "formatVersion": number;
    "installId": string;
    "gameId": string;
    "installPath": string;
    "gameVersion": string;
    "scannedAt": string;
    "defs": Def[] | null;
    "fieldInfo": { [_ in string]?: string } | null;
    "fieldInfoByKind": { [_ in string]?: { [_ in string]?: string } | null } | null;
    "structures": { [_ in string]?: string[] | null } | null;
    "structureBlocks"?: { [_ in string]?: string[] | null } | null;
    "vocabulary": string[] | null;
    "guiTypes": string[] | null;
    "guiProps": string[] | null;
    "metaKeys": string[] | null;
    "edges"?: Edge[] | null;
    "locRefs"?: Ref[] | null;

    /**
     * scripted_* call sites
     */
    "callRefs"?: Ref[] | null;
    "fieldValueKinds"?: { [_ in string]?: string } | null;
    "fieldEnumsByKind"?: { [_ in string]?: { [_ in string]?: string[] | null } | null } | null;
    "prefixKinds"?: { [_ in string]?: string } | null;
    "fireKeys"?: { [_ in string]?: string } | null;
    "nestedShapes"?: NestedShape[] | null;
    "wrappers"?: string[] | null;
    "locAffixes"?: { [_ in string]?: LocAffix[] | null } | null;
    "locFields"?: string[] | null;
    "locListFields"?: string[] | null;
    "locMemberAffixes"?: { [_ in string]?: LocAffix[] | null } | null;

    /**
     * LocKeyAffixes are shapes that derive one loc key from another, so a key
     * nothing cites is still explained. Not per kind: the stem is a key, not a def.
     */
    "locKeyAffixes"?: LocKeyAffix[] | null;
    "kindInfo"?: { [_ in string]?: string } | null;
    "dataFunctions"?: string[] | null;

    /**
     * LocEngineSlots are `$NAME$` interpolations the game's own localization
     * uses but never defines as a key — `$EFFECT_LIST_BULLET$`, `$ACTION$`,
     * `$AGE$`. The engine fills them in; they are not loc keys anyone can
     * write, so demanding one from a mod is a false "missing localization".
     * 
     * Derived from the install, never listed: 354 of the 1,138 distinct
     * ALL-CAPS interpolations in CK3's english loc are of this kind, and a game
     * update changes the set. `isLocEngineToken` guesses at the same thing from
     * shape (a single ALL-CAPS word) and is right about 80% of the time; this
     * is the measured version.
     */
    "locEngineSlots"?: string[] | null;

    /**
     * Schema is the type system the game declares in script_docs: scope types,
     * scope links, and typed engine tokens. Nil when the user has not run
     * script_docs; callers degrade rather than infer.
     */
    "schema"?: Schema | null;

    /**
     * KindScope maps a harvested database kind to the scope type it holds
     * (kind "cultures" → scope "culture"), resolved by bindKinds. This is what
     * lets completion filter effects by the scope the cursor sits in.
     */
    "kindScope"?: { [_ in string]?: string } | null;

    /**
     * Paths is the interning table for Def/Ref/Edge paths. It exists only on
     * disk: saveCacheFile writes it and loadCacheFile expands it away, so code
     * reading a cache always sees real paths.
     */
    "paths"?: string[] | null;
}
