// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDiff(arg1, arg2) {
  return window['go']['main']['App']['GetDiff'](arg1, arg2);
}

export function MergeMultipleFileSets(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MergeMultipleFileSets'](arg1, arg2, arg3, arg4);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectMultipleFiles(arg1, arg2) {
  return window['go']['main']['App']['SelectMultipleFiles'](arg1, arg2);
}

export function WriteMergedFile(arg1, arg2) {
  return window['go']['main']['App']['WriteMergedFile'](arg1, arg2);
}
