// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {patch} from '../models';
import {main} from '../models';

export function ComparePatches(arg1:string,arg2:string,arg3:Array<string>):Promise<patch.PatchComparison>;

export function GeneratePatchReport(arg1:patch.PatchComparison):Promise<string>;

export function GetDiffForFile(arg1:string,arg2:string,arg3:Record<string, any>):Promise<string>;

export function MergeMultipleFileSets(arg1:Array<string>,arg2:Array<string>,arg3:string,arg4:Record<string, any>):Promise<Array<main.FileMergeResult>>;

export function SaveDiffToFile(arg1:string,arg2:string):Promise<void>;

export function SavePatchReport(arg1:string,arg2:patch.PatchComparison):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectMultipleFiles(arg1:string,arg2:string):Promise<Array<string>>;

export function WriteMergedFile(arg1:string,arg2:string):Promise<void>;
