// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DetectedInstall is a game install found on disk.
 */
export interface DetectedInstall {
    "gameId": string;
    "name": string;
    "path": string;
    "version": string;
    "appId": number;
}
