// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DetectedInstall is a game install found on disk.
 */
export interface DetectedInstall {
    "gameId": string;
    "name": string;
    "path": string;
    "version": string;
    "appId": number;
}

/**
 * GameInfo is the static identity and convention set for one game. It carries no
 * derived data — the model package scans the install for objects, vocabulary, etc.
 */
export interface GameInfo {
    "id": string;
    "name": string;
    "shortName": string;

    /**
     * WikiAPI is the MediaWiki api.php endpoint for this game's wiki.
     */
    "wikiApi"?: string;

    /**
     * ScriptRoot is the install-relative folder holding script (e.g. "game").
     * EU5 still uses this: stages live under game/{in_game,main_menu,loading_screen}.
     * Mods omit game/ and put StageRoots at the mod root.
     */
    "scriptRoot"?: string;
    "stageRoots"?: string[] | null;

    /**
     * Descriptor is how a mod root is identified: "mod" (descriptor.mod) or
     * "metadata" (.metadata/metadata.json).
     */
    "descriptor"?: string;

    /**
     * DocsFolderName is the per-game Documents subfolder (e.g. "Crusader Kings III").
     */
    "docsFolderName"?: string;

    /**
     * ScriptDocsSubdir is where in-game console dumps land ("logs" or "docs").
     */
    "scriptDocsSubdir"?: string;

    /**
     * EntryModes are EU5 database entry-mode prefixes (INJECT:, REPLACE:, ...).
     */
    "entryModes"?: string[] | null;
    "steamAppId"?: number;

    /**
     * FirstWins is the FIOS sentence for Conflicts / Settings load-order copy.
     */
    "firstWins"?: string;
}

/**
 * GameList is the Wails payload for ListGames (consts are not exported).
 */
export interface GameList {
    "originVanilla": string;
    "games": (GameInfo | null)[] | null;
}
