// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * InventoryItemRow is a lightweight grid row.
 */
export interface InventoryItemRow {
    "key": string;
    "type": string;
    "filePath": string;
    "lineStart": number;
    "lineEnd": number;
    "referencesCount": number;
    "referrersCount": number;
}

/**
 * InventorySummary is a lightweight inventory listing.
 */
export interface InventorySummary {
    "id": string;
    "name": string;
    "game": string;
    "createdAt": string;
    "totalCount": number;
}

/**
 * ItemDetails is the full details for a single item.
 */
export interface ItemDetails {
    "rawText": string;
    "references": ObjectReference[] | null;
    "referrers": ObjectReference[] | null;
    "attributes": { [_ in string]?: boolean } | null;
}

/**
 * ObjectReference represents a reference between two game objects.
 */
export interface ObjectReference {
    "key": string;
    "type": string;
    "filePath": string;
    "lineStart"?: number;
    "lineEnd"?: number;
}
