// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Game represents a supported Paradox game.
 */
export interface Game {
    "id": string;
    "name": string;
    "wikiApi": string;
    "scriptRoot": string;
    "steamAppId": number;
}

/**
 * GameInstall represents a user-configured game installation.
 */
export interface GameInstall {
    "id": string;
    "gameId": string;
    "name": string;
    "path": string;
    "version": string;
    "docsPath": string;
    "isBroken": boolean;
    "createdAt": string;
}

/**
 * PatchRun represents a mod update campaign from baseline to target version.
 */
export interface PatchRun {
    "id": string;
    "workspaceId": string;
    "modId": string;
    "baselineVersion": string;
    "targetVersion": string;
    "baselineInstallId": string;
    "targetInstallId": string;
    "status": string;
    "stagingDir": string;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * PatchRunFile tracks per-file status within a patch run.
 */
export interface PatchRunFile {
    "id": string;
    "runId": string;
    "relPath": string;
    "status": string;
    "decision": string;
    "previewPath": string;
    "stats": string;
}

/**
 * Workspace is a user-defined mod working environment tied to a game.
 */
export interface Workspace {
    "id": string;
    "gameId": string;
    "name": string;
    "installId": string;
    "stagingDir": string;
    "tags": string;
    "thumbnailPath": string;
    "isActive": boolean;
    "createdAt": string;
}

/**
 * WorkspaceMod is a mod attached to a workspace.
 */
export interface WorkspaceMod {
    "id": string;
    "workspaceId": string;
    "name": string;
    "path": string;
    "isBroken": boolean;
    "createdAt": string;
}
