// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ClipboardService exposes the native clipboard to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * CopyToClipboard writes text to the system clipboard.
 */
export function CopyToClipboard(text: string): $CancellablePromise<boolean> {
    return $Call.ByID(447735729, text);
}

/**
 * ReadFromClipboard reads text from the system clipboard.
 */
export function ReadFromClipboard(): $CancellablePromise<string> {
    return $Call.ByID(341864297);
}
