// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DbService manages the SQLite database.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * ResetData wipes user data (workspaces, mods, installs, runs, indexes) but keeps games and app_settings.
 */
export function ResetData(): $CancellablePromise<void> {
    return $Call.ByID(2362858724);
}
