// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService provides directory/file selection dialogs and filesystem helpers for merge/IDE.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CollectAndMatchPaths collects files from both paths and returns matching pairs.
 */
export function CollectAndMatchPaths(pathA: string, pathB: string, filter: $models.FileCollectorFilter, matchByFilenameOnly: boolean): $CancellablePromise<{ [_ in string]?: $models.PathMatch } | null> {
    return $Call.ByID(1380774949, pathA, pathB, filter, matchByFilenameOnly);
}

/**
 * CollectFilesFromPath collects all .txt files from a mix of files and directories
 * Returns a map of relativePath -> fullPath
 */
export function CollectFilesFromPath(inputPath: string, filter: $models.FileCollectorFilter): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(2863705307, inputPath, filter);
}

/**
 * CreateDir creates a directory (parents created as needed).
 */
export function CreateDir(fullPath: string): $CancellablePromise<void> {
    return $Call.ByID(555002884, fullPath);
}

/**
 * DeletePath removes a file or directory recursively.
 */
export function DeletePath(fullPath: string): $CancellablePromise<void> {
    return $Call.ByID(3710022161, fullPath);
}

/**
 * FindMatchingPaths finds paths that exist in both sets. When matchByFilenameOnly is true,
 * matches only by filename (e.g. for zz_mod_file.txt where paths differ).
 */
export function FindMatchingPaths(filesA: { [_ in string]?: string } | null, filesB: { [_ in string]?: string } | null, matchByFilenameOnly: boolean): $CancellablePromise<{ [_ in string]?: $models.PathMatch } | null> {
    return $Call.ByID(2990739391, filesA, filesB, matchByFilenameOnly);
}

/**
 * GetUserDownloadsDir returns the user's Downloads directory (e.g. ~/Downloads).
 */
export function GetUserDownloadsDir(): $CancellablePromise<string> {
    return $Call.ByID(1105998516);
}

/**
 * ListDirectory lists immediate children of dirPath (non-recursive).
 * Shows all non-dot files and directories (binary included; editor handles view).
 */
export function ListDirectory(dirPath: string): $CancellablePromise<$models.DirEntry[] | null> {
    return $Call.ByID(2302512980, dirPath);
}

/**
 * ReadFileBase64 reads raw file bytes as standard base64 (binary-safe for the IDE bridge).
 */
export function ReadFileBase64(fullPath: string): $CancellablePromise<string> {
    return $Call.ByID(2750173100, fullPath);
}

/**
 * RenamePath renames or moves a file or directory.
 */
export function RenamePath(oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByID(1727956732, oldPath, newPath);
}

/**
 * SelectDirectory prompts for a folder. Cancel yields an empty path (no error).
 */
export function SelectDirectory(title: string): $CancellablePromise<string> {
    return $Call.ByID(421942968, title);
}

/**
 * SelectSingleFile prompts for a file. Cancel yields an empty path (no error).
 */
export function SelectSingleFile(title: string, filter: string): $CancellablePromise<string> {
    return $Call.ByID(430312767, title, filter);
}

/**
 * StatPath returns metadata for a path (Exists=false when missing, no error).
 */
export function StatPath(fullPath: string): $CancellablePromise<$models.PathStat> {
    return $Call.ByID(1964538536, fullPath);
}

/**
 * WriteFileBase64 writes raw bytes from standard base64.
 */
export function WriteFileBase64(fullPath: string, b64: string): $CancellablePromise<void> {
    return $Call.ByID(256026061, fullPath, b64);
}

/**
 * WriteWithBOM writes content to outputPath as UTF-8 with BOM. Creates parent directories as needed.
 */
export function WriteWithBOM(outputPath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(239287030, outputPath, content);
}
