// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService provides filesystem helpers for merge and the IDE workbench.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateDir creates a directory (parents created as needed).
 */
export function CreateDir(fullPath: string): $CancellablePromise<void> {
    return $Call.ByID(555002884, fullPath);
}

/**
 * DeletePath removes a file or directory recursively.
 */
export function DeletePath(fullPath: string): $CancellablePromise<void> {
    return $Call.ByID(3710022161, fullPath);
}

/**
 * FileSearch lists files whose path contains FilePattern (ripgrep --files).
 */
export function FileSearch(q: $models.FileSearchQuery): $CancellablePromise<$models.FileSearchResult> {
    return $Call.ByID(4261317059, q);
}

/**
 * GetUserDownloadsDir returns the user's Downloads directory (e.g. ~/Downloads).
 */
export function GetUserDownloadsDir(): $CancellablePromise<string> {
    return $Call.ByID(1105998516);
}

/**
 * ListDirectory lists immediate children of dirPath (non-recursive).
 * Shows all non-dot files and directories (binary included; editor handles view).
 */
export function ListDirectory(dirPath: string): $CancellablePromise<$models.DirEntry[] | null> {
    return $Call.ByID(2302512980, dirPath);
}

/**
 * ReadFileBase64 reads raw file bytes as standard base64, or Exists=false if missing.
 */
export function ReadFileBase64(fullPath: string): $CancellablePromise<$models.FileBytes> {
    return $Call.ByID(2750173100, fullPath);
}

/**
 * RenamePath renames or moves a file or directory.
 */
export function RenamePath(oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByID(1727956732, oldPath, newPath);
}

/**
 * StatPath returns metadata for a path (Exists=false when missing, no error).
 */
export function StatPath(fullPath: string): $CancellablePromise<$models.PathStat> {
    return $Call.ByID(1964538536, fullPath);
}

/**
 * TextSearch runs ripgrep --json, one process per folder.
 */
export function TextSearch(q: $models.TextSearchQuery): $CancellablePromise<$models.TextSearchResult> {
    return $Call.ByID(1211796934, q);
}

/**
 * WriteFileBase64 writes raw bytes from standard base64.
 */
export function WriteFileBase64(fullPath: string, b64: string): $CancellablePromise<void> {
    return $Call.ByID(256026061, fullPath, b64);
}
