// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GraphService searches definitions and walks reference edges.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetNeighbors returns definitions and edges touching key.
 */
export function GetNeighbors(workspaceID: string, key: string): $CancellablePromise<$models.NeighborResult | null> {
    return $Call.ByID(847310156, workspaceID, key);
}

/**
 * SearchDefinitions finds definitions by key/summary substring and optional type.
 */
export function SearchDefinitions(workspaceID: string, query: string, typeFilter: string): $CancellablePromise<$models.GraphDef[] | null> {
    return $Call.ByID(3787936843, workspaceID, query, typeFilter);
}

/**
 * SimulateCascade walks outgoing edges BFS from key up to maxDepth.
 */
export function SimulateCascade(workspaceID: string, key: string, maxDepth: number): $CancellablePromise<$models.CascadeNode[] | null> {
    return $Call.ByID(1051021117, workspaceID, key, maxDepth);
}
