// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * IdeService exposes editor Did* and LSP methods over Wails.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as lsp$0 from "./internal/lsp/models.js";

/**
 * CodeActions returns quick-fixes for the file.
 */
export function CodeActions(workspaceID: string, path: string): $CancellablePromise<lsp$0.CodeAction[] | null> {
    return $Call.ByID(1850891185, workspaceID, path);
}

/**
 * Complete returns completion items at a 0-based UTF-8 position.
 */
export function Complete(workspaceID: string, path: string, line: number, character: number): $CancellablePromise<lsp$0.CompletionItem[] | null> {
    return $Call.ByID(155217920, workspaceID, path, line, character);
}

/**
 * Definition returns go-to-definition locations.
 */
export function Definition(workspaceID: string, path: string, line: number, character: number): $CancellablePromise<lsp$0.Location[] | null> {
    return $Call.ByID(1771803486, workspaceID, path, line, character);
}

/**
 * Diagnose returns diagnostics for a file.
 */
export function Diagnose(workspaceID: string, path: string): $CancellablePromise<lsp$0.Diagnostic[] | null> {
    return $Call.ByID(2414394907, workspaceID, path);
}

/**
 * DidChange syncs buffer text into the session.
 */
export function DidChange(workspaceID: string, path: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(3111290104, workspaceID, path, text);
}

/**
 * DidClose drops an editor buffer overlay.
 */
export function DidClose(workspaceID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(1896704868, workspaceID, path);
}

/**
 * DidOpen syncs an editor buffer into the session.
 */
export function DidOpen(workspaceID: string, path: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(500946888, workspaceID, path, text);
}

/**
 * DidSave reindexes path from its buffer or disk.
 */
export function DidSave(workspaceID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(2784970589, workspaceID, path);
}

/**
 * DocumentSymbols returns top-level symbols in a file.
 */
export function DocumentSymbols(workspaceID: string, path: string): $CancellablePromise<lsp$0.SymbolInformation[] | null> {
    return $Call.ByID(2046626823, workspaceID, path);
}

/**
 * FoldingRanges returns foldable block ranges.
 */
export function FoldingRanges(workspaceID: string, path: string): $CancellablePromise<lsp$0.FoldingRange[] | null> {
    return $Call.ByID(2841121370, workspaceID, path);
}

/**
 * FormatDocument returns conservative format edits.
 */
export function FormatDocument(workspaceID: string, path: string): $CancellablePromise<lsp$0.TextEdit[] | null> {
    return $Call.ByID(3770361501, workspaceID, path);
}

/**
 * Hover returns hover info at a 0-based UTF-8 position.
 */
export function Hover(workspaceID: string, path: string, line: number, character: number): $CancellablePromise<lsp$0.HoverResult | null> {
    return $Call.ByID(4183822451, workspaceID, path, line, character);
}

/**
 * References returns reference locations.
 */
export function References(workspaceID: string, path: string, line: number, character: number): $CancellablePromise<lsp$0.Location[] | null> {
    return $Call.ByID(3329907361, workspaceID, path, line, character);
}

/**
 * Rename returns a workspace edit for the identifier at pos.
 */
export function Rename(workspaceID: string, path: string, line: number, character: number, newName: string): $CancellablePromise<lsp$0.WorkspaceEdit | null> {
    return $Call.ByID(732777145, workspaceID, path, line, character, newName);
}

/**
 * SignatureHelp returns usage-based signature help at a 0-based UTF-8 position.
 */
export function SignatureHelp(workspaceID: string, path: string, line: number, character: number): $CancellablePromise<lsp$0.SignatureHelpResult | null> {
    return $Call.ByID(4126214260, workspaceID, path, line, character);
}

/**
 * WorkspaceSymbols searches definitions in the session.
 */
export function WorkspaceSymbols(workspaceID: string, query: string): $CancellablePromise<lsp$0.SymbolInformation[] | null> {
    return $Call.ByID(4029298109, workspaceID, query);
}
