// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * IndexerService indexes game and mod script objects for search and cascade analysis.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as repos$0 from "./internal/repos/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BuildEventEdges creates edges for event triggers and immediates.
 */
export function BuildEventEdges(workspaceID: string): $CancellablePromise<number> {
    return $Call.ByID(1403223366, workspaceID);
}

/**
 * CancelIndex cancels an in-flight ReindexWorkspace job.
 */
export function CancelIndex(): $CancellablePromise<void> {
    return $Call.ByID(1656578858);
}

/**
 * CountIndexObjects returns how many objects are indexed for a workspace.
 */
export function CountIndexObjects(workspaceID: string): $CancellablePromise<number> {
    return $Call.ByID(2345134055, workspaceID);
}

/**
 * ListIndexObjects returns all objects for a workspace, optionally filtered by type.
 */
export function ListIndexObjects(workspaceID: string, typeFilter: string): $CancellablePromise<repos$0.IndexObject[] | null> {
    return $Call.ByID(49719940, workspaceID, typeFilter);
}

/**
 * ReindexWorkspace walks game+mod roots, parses scripts and loc, stores index_objects.
 */
export function ReindexWorkspace(workspaceID: string): $CancellablePromise<number> {
    return $Call.ByID(1584617056, workspaceID);
}

/**
 * SearchIndex searches indexed objects by key pattern.
 */
export function SearchIndex(workspaceID: string, query: string): $CancellablePromise<repos$0.IndexObject[] | null> {
    return $Call.ByID(54284788, workspaceID, query);
}

/**
 * SimulateCascade walks edges BFS from startKey up to maxDepth.
 */
export function SimulateCascade(workspaceID: string, startKey: string, maxDepth: number): $CancellablePromise<$models.CascadeNode[] | null> {
    return $Call.ByID(2200797048, workspaceID, startKey, maxDepth);
}
