// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * InventoryService exposes inventory functionality to the Wails frontend (supported types, schema, extraction, save, list).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteInventory removes an inventory and its items (cascade).
 */
export function DeleteInventory(id: string): $CancellablePromise<void> {
    return $Call.ByID(2271082920, id);
}

/**
 * ExtractInventory extracts inventory items from basePath that match objectTypes. Writes to DB as temporary; returns inventoryId and totalCount. Only .txt files are processed. Deletes prior temporary inventories before inserting.
 */
export function ExtractInventory(game: string, basePath: string, objectTypes: string[] | null): $CancellablePromise<string | null> {
    return $Call.ByID(383781064, game, basePath, objectTypes);
}

/**
 * GetAttributes returns the list of attribute names for an object type and game.
 */
export function GetAttributes(game: string, typeName: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3409867136, game, typeName);
}

/**
 * GetInventoryItems returns lightweight rows for the grid (no raw_text, references, referrers).
 */
export function GetInventoryItems(inventoryId: string): $CancellablePromise<$models.InventoryItemRow[] | null> {
    return $Call.ByID(3075356477, inventoryId);
}

/**
 * GetItemDetails returns full details for a single item (on row selection).
 */
export function GetItemDetails(inventoryId: string, itemType: string, itemKey: string): $CancellablePromise<$models.ItemDetails | null> {
    return $Call.ByID(3246543216, inventoryId, itemType, itemKey);
}

/**
 * GetSupportedTypes returns the sorted list of object type names for the given game.
 */
export function GetSupportedTypes(game: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1823722162, game);
}

/**
 * ListInventoriesForGame returns saved (non-temporary) inventories for the given game, ordered by created_at DESC.
 */
export function ListInventoriesForGame(game: string): $CancellablePromise<$models.InventorySummary[] | null> {
    return $Call.ByID(328231442, game);
}

/**
 * RenameInventory updates the inventory name.
 */
export function RenameInventory(id: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(2871905135, id, newName);
}

/**
 * SaveInventory marks an inventory as saved (persists name and sets is_temporary=0).
 */
export function SaveInventory(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3151461374, id, name);
}
