// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LanguageModelService builds JSON workspace models and serves LSP-style queries.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as lsp$0 from "./internal/lsp/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel cancels an in-flight RebuildWorkspaceModel job.
 */
export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(2061479282);
}

/**
 * Complete returns completion items at a 0-based position.
 */
export function Complete(workspaceID: string, path: string, line: number, character: number): $CancellablePromise<lsp$0.CompletionItem[] | null> {
    return $Call.ByID(2413782175, workspaceID, path, line, character);
}

/**
 * Definition returns go-to-definition locations.
 */
export function Definition(workspaceID: string, path: string, line: number, character: number): $CancellablePromise<lsp$0.Location[] | null> {
    return $Call.ByID(896958585, workspaceID, path, line, character);
}

/**
 * Diagnose returns parse diagnostics for a script file.
 */
export function Diagnose(path: string): $CancellablePromise<lsp$0.Diagnostic[] | null> {
    return $Call.ByID(260373792, path);
}

/**
 * DocumentSymbols returns top-level symbols in a file.
 */
export function DocumentSymbols(path: string): $CancellablePromise<lsp$0.SymbolInformation[] | null> {
    return $Call.ByID(1584417218, path);
}

/**
 * GetModelStatus returns cache presence for a workspace.
 */
export function GetModelStatus(workspaceID: string): $CancellablePromise<$models.ModelStatus | null> {
    return $Call.ByID(4031817715, workspaceID);
}

/**
 * Hover returns hover info at a 0-based LSP position using the workspace model.
 */
export function Hover(workspaceID: string, path: string, line: number, character: number): $CancellablePromise<lsp$0.HoverResult | null> {
    return $Call.ByID(3898042650, workspaceID, path, line, character);
}

/**
 * RebuildWorkspaceModel walks install/mod/staging roots and writes the JSON model.
 */
export function RebuildWorkspaceModel(workspaceID: string): $CancellablePromise<number> {
    return $Call.ByID(3173802769, workspaceID);
}

/**
 * References returns reference locations.
 */
export function References(workspaceID: string, path: string, line: number, character: number): $CancellablePromise<lsp$0.Location[] | null> {
    return $Call.ByID(3741175570, workspaceID, path, line, character);
}

/**
 * WorkspaceSymbols searches definitions in the workspace model.
 */
export function WorkspaceSymbols(workspaceID: string, query: string): $CancellablePromise<lsp$0.SymbolInformation[] | null> {
    return $Call.ByID(1330926086, workspaceID, query);
}
