// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LanguageModelService exposes the language engine to the frontend over Wails.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as graph$0 from "./internal/graph/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as lsp$0 from "./internal/lsp/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "./internal/model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel cancels an in-flight install scan.
 */
export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(2061479282);
}

/**
 * CodeActions returns quick-fixes for the file.
 */
export function CodeActions(workspaceID: string, path: string): $CancellablePromise<lsp$0.CodeAction[] | null> {
    return $Call.ByID(435066492, workspaceID, path);
}

/**
 * Complete returns completion items at a 0-based UTF-8 position.
 */
export function Complete(workspaceID: string, path: string, line: number, character: number): $CancellablePromise<lsp$0.CompletionItem[] | null> {
    return $Call.ByID(2413782175, workspaceID, path, line, character);
}

/**
 * Definition returns go-to-definition locations.
 */
export function Definition(workspaceID: string, path: string, line: number, character: number): $CancellablePromise<lsp$0.Location[] | null> {
    return $Call.ByID(896958585, workspaceID, path, line, character);
}

/**
 * Diagnose returns diagnostics for a file.
 */
export function Diagnose(workspaceID: string, path: string): $CancellablePromise<lsp$0.Diagnostic[] | null> {
    return $Call.ByID(260373792, workspaceID, path);
}

/**
 * DidChange syncs buffer text into the session.
 */
export function DidChange(workspaceID: string, path: string, text: string, languageID: string, version: number): $CancellablePromise<void> {
    return $Call.ByID(3887593753, workspaceID, path, text, languageID, version);
}

/**
 * DidClose drops an editor buffer overlay.
 */
export function DidClose(workspaceID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(2506421591, workspaceID, path);
}

/**
 * DidOpen syncs an editor buffer into the session.
 */
export function DidOpen(workspaceID: string, path: string, text: string, languageID: string, version: number): $CancellablePromise<void> {
    return $Call.ByID(717537189, workspaceID, path, text, languageID, version);
}

/**
 * DidSave reindexes path from its buffer or disk.
 */
export function DidSave(workspaceID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(72813964, workspaceID, path);
}

/**
 * DocumentSymbols returns top-level symbols in a file.
 */
export function DocumentSymbols(workspaceID: string, path: string): $CancellablePromise<lsp$0.SymbolInformation[] | null> {
    return $Call.ByID(1584417218, workspaceID, path);
}

/**
 * EnsureSession builds or returns the live session for workspaceID.
 */
export function EnsureSession(workspaceID: string): $CancellablePromise<void> {
    return $Call.ByID(3236884274, workspaceID);
}

/**
 * FoldingRanges returns foldable block ranges.
 */
export function FoldingRanges(workspaceID: string, path: string): $CancellablePromise<lsp$0.FoldingRange[] | null> {
    return $Call.ByID(3289648599, workspaceID, path);
}

/**
 * FormatDocument returns conservative format edits.
 */
export function FormatDocument(workspaceID: string, path: string): $CancellablePromise<lsp$0.TextEdit[] | null> {
    return $Call.ByID(2131978046, workspaceID, path);
}

/**
 * GetDependencies returns dependents and inner references for one definition.
 */
export function GetDependencies(workspaceID: string, name: string, kind: string): $CancellablePromise<graph$0.Dependencies> {
    return $Call.ByID(2369697169, workspaceID, name, kind);
}

/**
 * GetEventDetail returns inspector content for one event id.
 */
export function GetEventDetail(workspaceID: string, eventID: string): $CancellablePromise<graph$0.EventDetail | null> {
    return $Call.ByID(80590861, workspaceID, eventID);
}

/**
 * GetEventGraph returns the defs-first event graph (no coordinates).
 */
export function GetEventGraph(workspaceID: string, params: graph$0.EventGraphParams): $CancellablePromise<graph$0.EventGraph> {
    return $Call.ByID(90600752, workspaceID, params);
}

/**
 * GetLanguageHealth returns install/cache/index status for the workspace.
 */
export function GetLanguageHealth(workspaceID: string): $CancellablePromise<$models.LanguageHealth | null> {
    return $Call.ByID(3308847756, workspaceID);
}

/**
 * GetLocCoverage returns per-language localization health for workspace mods.
 */
export function GetLocCoverage(workspaceID: string): $CancellablePromise<graph$0.LocCoverage[] | null> {
    return $Call.ByID(1047711728, workspaceID);
}

/**
 * GetModelStatus reports live session (or on-disk index) readiness.
 */
export function GetModelStatus(workspaceID: string): $CancellablePromise<$models.ModelStatus | null> {
    return $Call.ByID(4031817715, workspaceID);
}

/**
 * GetOverrides returns FIOS/LIOS override rows for the conflict monitor.
 */
export function GetOverrides(workspaceID: string): $CancellablePromise<model$0.OverrideRow[] | null> {
    return $Call.ByID(619790509, workspaceID);
}

/**
 * Hover returns hover info at a 0-based UTF-8 position.
 */
export function Hover(workspaceID: string, path: string, line: number, character: number): $CancellablePromise<lsp$0.HoverResult | null> {
    return $Call.ByID(3898042650, workspaceID, path, line, character);
}

/**
 * LaunchGameDebug starts the game with debug flags (best-effort).
 */
export function LaunchGameDebug(workspaceID: string): $CancellablePromise<void> {
    return $Call.ByID(125062164, workspaceID);
}

/**
 * LookupLoc returns the english loc text and site for key.
 */
export function LookupLoc(workspaceID: string, key: string): $CancellablePromise<graph$0.LocLookup | null> {
    return $Call.ByID(4044889144, workspaceID, key);
}

/**
 * RebuildWorkspaceSemantics scans the workspace install into a vanilla Cache.
 */
export function RebuildWorkspaceSemantics(workspaceID: string): $CancellablePromise<model$0.Cache | null> {
    return $Call.ByID(3647214449, workspaceID);
}

/**
 * References returns reference locations.
 */
export function References(workspaceID: string, path: string, line: number, character: number): $CancellablePromise<lsp$0.Location[] | null> {
    return $Call.ByID(3741175570, workspaceID, path, line, character);
}

/**
 * Rename returns a workspace edit for the identifier at pos.
 */
export function Rename(workspaceID: string, path: string, line: number, character: number, newName: string): $CancellablePromise<lsp$0.WorkspaceEdit | null> {
    return $Call.ByID(3163683066, workspaceID, path, line, character, newName);
}

/**
 * SignatureHelp returns a signature tooltip.
 */
export function SignatureHelp(workspaceID: string, path: string, line: number, character: number): $CancellablePromise<lsp$0.SignatureHelp | null> {
    return $Call.ByID(259431861, workspaceID, path, line, character);
}

/**
 * WorkspaceSymbols searches definitions in the session.
 */
export function WorkspaceSymbols(workspaceID: string, query: string): $CancellablePromise<lsp$0.SymbolInformation[] | null> {
    return $Call.ByID(1330926086, workspaceID, query);
}
