// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LocService lint and auto-loc for workspace mods.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AutoLocalize copies missing keys from sourceLang into targetLang under the first mod.
 */
export function AutoLocalize(workspaceID: string, sourceLang: string, targetLang: string, modID: string): $CancellablePromise<$models.AutoLocResult | null> {
    return $Call.ByID(156423917, workspaceID, sourceLang, targetLang, modID);
}

/**
 * LintMissingLoc finds script loc refs missing from the target language.
 */
export function LintMissingLoc(workspaceID: string, language: string): $CancellablePromise<$models.LocDiagnostic[] | null> {
    return $Call.ByID(3359939626, workspaceID, language);
}
