// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MergeService merges matching script files from two path sets into an output directory using core merge logic.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Merge performs the merge for each task (PreviewItem) and writes results. Single entry point for merge operations.
 */
export function Merge(tasks: $models.PreviewItem[] | null, opts: $models.MergerOptions): $CancellablePromise<$models.FileMergeResult[] | null> {
    return $Call.ByID(2042205069, tasks, opts);
}

/**
 * MergePreview collects matching files from pathA/pathB and returns preview items with output paths.
 */
export function MergePreview(pathA: string, pathB: string, outputDir: string): $CancellablePromise<$models.PreviewItem[] | null> {
    return $Call.ByID(2633360575, pathA, pathB, outputDir);
}
