// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetDocContent returns the content of a doc file from doc_files.
 */
export function GetDocContent(game: string, installPath: string, relPath: string): $CancellablePromise<string> {
    return $Call.ByID(1072141760, game, installPath, relPath);
}

/**
 * GetDocPathCache returns the doc path list from doc_files for the game+install path.
 */
export function GetDocPathCache(game: string, installPath: string): $CancellablePromise<$models.DocPathCache | null> {
    return $Call.ByID(4098167898, game, installPath);
}

export function Scan(game: string, installPath: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3940026476, game, installPath);
}
