// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as langmodel$0 from "./internal/langmodel/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as repos$0 from "./internal/repos/models.js";

/**
 * CascadeNode represents a node in cascade simulation results.
 */
export interface CascadeNode {
    "key": string;
    "depth": number;
    "edgeType"?: string;
    "children"?: string[] | null;
}

/**
 * DirEntry is one immediate child of a directory (for lazy file trees).
 */
export interface DirEntry {
    "name": string;
    "relPath": string;
    "fullPath": string;
    "isDir": boolean;
}

export interface FileCollectorFilter {
    /**
     * e.g. [".txt", ".lua"]
     */
    "Extensions": string[] | null;

    /**
     * e.g. ["readme.txt", "mod.lua"]
     */
    "FileNames": string[] | null;

    /**
     * e.g. "^(readme|mod)\.txt$"
     */
    "Regex": string;

    /**
     * regex on rel path, e.g. "events/" - include only if matches
     */
    "IncludePath": string;

    /**
     * regex on rel path, e.g. "common/" - exclude if matches
     */
    "ExcludePath": string;
}

/**
 * FileMergeResult is the result of merging one file.
 */
export interface FileMergeResult {
    "filePath": string;
    "fileAPath": string;
    "fileBPath": string;
    "outputPath": string;
    "changed": number;
    "added": number;
    "entriesChanged"?: string[] | null;
    "entriesAdded"?: string[] | null;
    "resolvedConflicts"?: ResolvedConflict[] | null;
    "error"?: string;
}

/**
 * GraphDef is a definition returned to the frontend.
 */
export interface GraphDef {
    "type": string;
    "key": string;
    "filePath": string;
    "line": number;
    "col": number;
    "endLine": number;
    "summary": string;
}

/**
 * GraphEdge is a reference edge between keys.
 */
export interface GraphEdge {
    "fromKey": string;
    "toKey": string;
    "edgeType": string;
}

/**
 * MergePreset holds a named merge options profile (JSON-safe for bindings)
 */
export interface MergePreset {
    "name": string;
    "options": MergerOptions;
}

/**
 * MergerOptions configures how files are merged.
 */
export interface MergerOptions {
    "addAdditionalEntries": boolean;
    "manualConflictResolution": boolean;
    "keyList": string[] | null;
    "matchByFilenameOnly": boolean;
    "includePathPattern": string;
    "excludePathPattern": string;

    /**
     * e.g. "_merged" meaning: events/foo.txt -> events/foo_merged.txt
     */
    "outputFileSuffix": string;
    "outputDir": string;
}

/**
 * ModelStatus reports whether a cached language model exists.
 */
export type ModelStatus = langmodel$0.Status;

/**
 * NeighborResult is a key plus its inbound/outbound edges.
 */
export interface NeighborResult {
    "key": string;
    "defs": GraphDef[] | null;
    "outgoing": GraphEdge[] | null;
    "incoming": GraphEdge[] | null;
}

/**
 * PatchRunPreview is the result of previewing a patch run.
 */
export interface PatchRunPreview {
    "runId": string;
    "files": repos$0.PatchRunFile[] | null;
    "totalFiles": number;
    "safeCount": number;
    "reviewCount": number;
    "skippedCount": number;
}

/**
 * PatchVersion is a lightweight version entry from the version index.
 */
export interface PatchVersion {
    "version": string;
    "url": string;
}

/**
 * FileMatch represents a matched path pair
 */
export interface PathMatch {
    "pathA": string;
    "pathB": string;
}

/**
 * PathStat describes a filesystem node for the workbench FS bridge.
 */
export interface PathStat {
    "exists": boolean;
    "isDir": boolean;
    "size": number;
    "mtimeMs": number;
    "ctimeMs": number;
}

/**
 * PreviewItem is a single file match for the merge preview.
 */
export interface PreviewItem {
    "relPath": string;
    "pathA": string;
    "pathB": string;
    "outputPath": string;
    "wouldOverwrite": boolean;
}

/**
 * ResolvedConflict records a conflict that was auto-resolved (for report/audit).
 */
export interface ResolvedConflict {
    "key": string;

    /**
     * "A" or "B"
     */
    "usedSide": string;

    /**
     * "directive", "keyList", "default"
     */
    "reason": string;
}

/**
 * SemanticsStatus reports whether a cached semantic model exists for an install.
 */
export interface SemanticsStatus {
    "present": boolean;
    "installId": string;
    "gameId"?: string;
    "scannedAt"?: string;
    "path"?: string;
}
