// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as repos$0 from "./internal/repos/models.js";

/**
 * DocPathCache is the cached doc path list for a game+install path (JSON-safe for bindings).
 */
export interface DocPathCache {
    "paths": string[] | null;
    "scannedAt": string;
    "installPath": string;
}

export interface FileCollectorFilter {
    /**
     * e.g. [".txt", ".lua"]
     */
    "Extensions": string[] | null;

    /**
     * e.g. ["readme.txt", "mod.lua"]
     */
    "FileNames": string[] | null;

    /**
     * e.g. "^(readme|mod)\.txt$"
     */
    "Regex": string;

    /**
     * regex on rel path, e.g. "events/" - include only if matches
     */
    "IncludePath": string;

    /**
     * regex on rel path, e.g. "common/" - exclude if matches
     */
    "ExcludePath": string;
}

/**
 * FileMergeResult is the result of merging one file.
 */
export interface FileMergeResult {
    "filePath": string;
    "fileAPath": string;
    "fileBPath": string;
    "outputPath": string;
    "changed": number;
    "added": number;
    "entriesChanged"?: string[] | null;
    "entriesAdded"?: string[] | null;
    "resolvedConflicts"?: ResolvedConflict[] | null;
    "error"?: string;
}

export type InventoryItemRow = repos$0.InventoryItemRow;

export type InventorySummary = repos$0.InventorySummary;

export type ItemDetails = repos$0.ItemDetails;

/**
 * LatestPatchNotes is the latest patch notes entry for a game (JSON-safe for bindings).
 */
export interface LatestPatchNotes {
    "url": string;
    "title": string;
    "contents": string;
}

/**
 * MergePreset holds a named merge options profile (JSON-safe for bindings)
 */
export interface MergePreset {
    "name": string;
    "options": MergerOptions;
}

/**
 * MergerOptions configures how files are merged.
 */
export interface MergerOptions {
    "addAdditionalEntries": boolean;
    "manualConflictResolution": boolean;
    "keyList": string[] | null;
    "matchByFilenameOnly": boolean;
    "includePathPattern": string;
    "excludePathPattern": string;

    /**
     * e.g. "_merged" meaning: events/foo.txt -> events/foo_merged.txt
     */
    "outputFileSuffix": string;
    "outputDir": string;
}

/**
 * FileMatch represents a matched path pair
 */
export interface PathMatch {
    "pathA": string;
    "pathB": string;
}

/**
 * PreviewItem is a single file match for the merge preview.
 */
export interface PreviewItem {
    "relPath": string;
    "pathA": string;
    "pathB": string;
    "outputPath": string;
    "wouldOverwrite": boolean;
}

/**
 * ResolvedConflict records a conflict that was auto-resolved (for report/audit).
 */
export interface ResolvedConflict {
    "key": string;

    /**
     * "A" or "B"
     */
    "usedSide": string;

    /**
     * "directive", "keyList", "default"
     */
    "reason": string;
}

export interface TreeNode {
    "relPath": string;
    "name": string;
    "children": TreeNode[] | null;
}

/**
 * ValidationError describes a parse error in a merged file.
 */
export interface ValidationError {
    "path": string;
    "line": number;
    "error": string;
}
