// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PatcherService manages mod version patching/update campaigns.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as repos$0 from "./internal/repos/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyPatchRun applies accepted changes from a patch run to the mod.
 */
export function ApplyPatchRun(runID: string): $CancellablePromise<void> {
    return $Call.ByID(3568122785, runID);
}

/**
 * GetPatchRun returns a patch run by ID.
 */
export function GetPatchRun(runID: string): $CancellablePromise<repos$0.PatchRun | null> {
    return $Call.ByID(3632148045, runID);
}

/**
 * GetPatchRunFiles returns all files for a patch run.
 */
export function GetPatchRunFiles(runID: string): $CancellablePromise<repos$0.PatchRunFile[] | null> {
    return $Call.ByID(3135171880, runID);
}

/**
 * ListPatchRuns returns all patch runs for a workspace.
 */
export function ListPatchRuns(workspaceID: string): $CancellablePromise<repos$0.PatchRun[] | null> {
    return $Call.ByID(151479946, workspaceID);
}

/**
 * PreviewPatchRun scans mod vs target vanilla, classifies files, writes preview staging.
 */
export function PreviewPatchRun(runID: string): $CancellablePromise<$models.PatchRunPreview | null> {
    return $Call.ByID(1294902629, runID);
}

/**
 * SetFileDecision sets the user decision for a patch run file.
 */
export function SetFileDecision(fileID: string, decision: string): $CancellablePromise<void> {
    return $Call.ByID(3500025182, fileID, decision);
}

/**
 * StartPatchRun creates a new patch run for a mod.
 */
export function StartPatchRun(workspaceID: string, modID: string, baselineVersion: string, targetVersion: string, baselineInstallID: string, targetInstallID: string): $CancellablePromise<repos$0.PatchRun | null> {
    return $Call.ByID(1577797481, workspaceID, modID, baselineVersion, targetVersion, baselineInstallID, targetInstallID);
}
