// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PatcherService manages mod version patching.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyPatchRun applies accepted changes from a patch run to the mod.
 */
export function ApplyPatchRun(runID: string): $CancellablePromise<void> {
    return $Call.ByID(3568122785, runID);
}

/**
 * PreviewPatchRun scans mod vs target vanilla, classifies files, writes preview staging.
 */
export function PreviewPatchRun(runID: string): $CancellablePromise<$models.PatchRunPreview | null> {
    return $Call.ByID(1294902629, runID);
}

/**
 * SetFileDecision sets the user decision for a patch run file.
 */
export function SetFileDecision(fileID: string, decision: string): $CancellablePromise<void> {
    return $Call.ByID(3500025182, fileID, decision);
}

/**
 * StartPatchRun creates a new patch run for a mod.
 */
export function StartPatchRun(workspaceID: string, modID: string, targetVersion: string, targetInstallID: string): $CancellablePromise<$models.PatchRun | null> {
    return $Call.ByID(1577797481, workspaceID, modID, targetVersion, targetInstallID);
}
