// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ReleaseService loads and saves mod listing files and execs pmt-steamugc.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddWorkshopPreview copies an image into workshop/previews (Steam extra cap).
 */
export function AddWorkshopPreview(workspaceID: string, modID: string, srcPath: string): $CancellablePromise<$models.Listing | null> {
    return $Call.ByID(4111048788, workspaceID, modID, srcPath);
}

/**
 * AddWorkshopVideo appends a YouTube id from a watch/embed/youtu.be URL or raw id.
 */
export function AddWorkshopVideo(workspaceID: string, modID: string, urlOrID: string): $CancellablePromise<$models.Listing | null> {
    return $Call.ByID(3064931667, workspaceID, modID, urlOrID);
}

/**
 * BumpVersion returns a bumped descriptor version (kind: patch|minor).
 */
export function BumpVersion(current: string, kind: string): $CancellablePromise<string> {
    return $Call.ByID(3779889750, current, kind);
}

/**
 * Convert maps listing markup. UI writes Markdown and asks for "bbcode".
 */
export function Convert(src: string, to: string): $CancellablePromise<$models.ConvertResult> {
    return $Call.ByID(599949017, src, to);
}

/**
 * CopyThumbnail copies src onto the game thumb path and returns the new rel.
 */
export function CopyThumbnail(workspaceID: string, modID: string, src: string): $CancellablePromise<string> {
    return $Call.ByID(909999901, workspaceID, modID, src);
}

/**
 * DraftChangelog returns a version stub for the Steam change note field.
 */
export function DraftChangelog(workspaceID: string, modID: string, version: string): $CancellablePromise<string> {
    return $Call.ByID(2949102389, workspaceID, modID, version);
}

/**
 * LoadListing reads descriptor + readmes for a workspace mod.
 */
export function LoadListing(workspaceID: string, modID: string): $CancellablePromise<$models.Listing | null> {
    return $Call.ByID(479006178, workspaceID, modID);
}

/**
 * PublishSteam saves the listing, publishes to Steam, then saves again with the workshop id.
 */
export function PublishSteam($in: $models.Listing): $CancellablePromise<$models.PublishResult | null> {
    return $Call.ByID(2912840271, $in);
}

/**
 * RemoveWorkshopPreview deletes one extra image under workshop/previews.
 */
export function RemoveWorkshopPreview(workspaceID: string, modID: string, rel: string): $CancellablePromise<$models.Listing | null> {
    return $Call.ByID(2120077753, workspaceID, modID, rel);
}

/**
 * RemoveWorkshopVideo drops one YouTube id from workshop/videos.txt.
 */
export function RemoveWorkshopVideo(workspaceID: string, modID: string, id: string): $CancellablePromise<$models.Listing | null> {
    return $Call.ByID(1658939442, workspaceID, modID, id);
}

/**
 * SaveListing writes descriptor, description files, optional thumb, and changelog.
 */
export function SaveListing($in: $models.Listing): $CancellablePromise<$models.Listing | null> {
    return $Call.ByID(746970025, $in);
}
