// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ScriptLogService handles game error.log imports and analysis.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as repos$0 from "./internal/repos/models.js";

/**
 * GetScriptLogImport returns a specific import by ID.
 */
export function GetScriptLogImport(importID: string): $CancellablePromise<repos$0.ScriptLogImport | null> {
    return $Call.ByID(1934602738, importID);
}

/**
 * ImportScriptLog reads a game script log (error.log), extracts summary, stores in DB.
 */
export function ImportScriptLog(workspaceID: string, path: string): $CancellablePromise<repos$0.ScriptLogImport | null> {
    return $Call.ByID(1563548020, workspaceID, path);
}

/**
 * ListScriptLogImports returns all imports for a workspace.
 */
export function ListScriptLogImports(workspaceID: string): $CancellablePromise<repos$0.ScriptLogImport[] | null> {
    return $Call.ByID(740221943, workspaceID);
}
