// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SearchService is the Wails RPC shell for Find in Files. FileService stays FS CRUD.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * FileSearch lists files whose path contains FilePattern under workspace folders.
 */
export function FileSearch(q: $models.FileSearchQuery): $CancellablePromise<$models.FileSearchResult> {
    return $Call.ByID(3021161365, q);
}

/**
 * TextSearch walks workspace folders and greps file bodies in-process.
 */
export function TextSearch(q: $models.TextSearchQuery): $CancellablePromise<$models.TextSearchResult> {
    return $Call.ByID(1024315628, q);
}
