// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SemanticsService rebuilds and applies per-install semantic caches.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scanner$0 from "./internal/semantics/scanner/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelSemantics cancels an in-flight RebuildSemantics job.
 */
export function CancelSemantics(): $CancellablePromise<void> {
    return $Call.ByID(941788229);
}

/**
 * GetSemanticsStatus returns cache presence for a workspace's linked install.
 */
export function GetSemanticsStatus(workspaceID: string): $CancellablePromise<$models.SemanticsStatus | null> {
    return $Call.ByID(3352689409, workspaceID);
}

/**
 * LoadSemanticsCache returns the saved cache for an install if present.
 */
export function LoadSemanticsCache(installID: string): $CancellablePromise<scanner$0.Cache | null> {
    return $Call.ByID(3326710847, installID);
}

/**
 * RebuildSemantics scans a game install and writes/applies the cache.
 */
export function RebuildSemantics(installID: string): $CancellablePromise<scanner$0.Cache | null> {
    return $Call.ByID(3128722214, installID);
}

/**
 * RebuildWorkspaceSemantics rebuilds for the workspace's linked install.
 */
export function RebuildWorkspaceSemantics(workspaceID: string): $CancellablePromise<scanner$0.Cache | null> {
    return $Call.ByID(1676203007, workspaceID);
}
