// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionService owns the session pool and install-scan RPC.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as catalog$0 from "./internal/catalog/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * EnsureSession builds or returns the live session for workspaceID.
 */
export function EnsureSession(workspaceID: string): $CancellablePromise<void> {
    return $Call.ByID(2736629943, workspaceID);
}

/**
 * GetLanguageHealth returns install/cache/session status for the workspace.
 */
export function GetLanguageHealth(workspaceID: string): $CancellablePromise<$models.LanguageHealth | null> {
    return $Call.ByID(1851235705, workspaceID);
}

/**
 * GetModelStatus reports whether a live session exists for the workspace.
 */
export function GetModelStatus(workspaceID: string): $CancellablePromise<$models.ModelStatus | null> {
    return $Call.ByID(4011313920, workspaceID);
}

/**
 * RebuildInstallSemantics scans an install into VanillaCache + loc sidecar.
 */
export function RebuildInstallSemantics(installID: string): $CancellablePromise<catalog$0.VanillaCache | null> {
    return $Call.ByID(521221046, installID);
}
