// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService provides persisted app settings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function CheckForUpdates(): $CancellablePromise<void> {
    return $Call.ByID(2389207713);
}

/**
 * GetSettings loads settings as a map "game.key" -> value.
 */
export function GetSettings(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(1419253203);
}

export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(2937747050);
}

/**
 * ResetData wipes workspaces, mods, installs, patch runs, and the semantic cache.
 */
export function ResetData(): $CancellablePromise<void> {
    return $Call.ByID(2171932109);
}

/**
 * SaveSettings writes user settings to app_settings table.
 */
export function SaveSettings(settings: { [_ in string]?: string } | null): $CancellablePromise<void> {
    return $Call.ByID(3145424170, settings);
}
