// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService provides persisted app settings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckForUpdates(): $CancellablePromise<void> {
    return $Call.ByID(2389207713);
}

/**
 * DeleteMergePreset removes a preset by name.
 */
export function DeleteMergePreset(name: string): $CancellablePromise<void> {
    return $Call.ByID(241571328, name);
}

/**
 * GetMergePresets returns saved merge presets from app_settings.
 */
export function GetMergePresets(): $CancellablePromise<$models.MergePreset[] | null> {
    return $Call.ByID(3580251362);
}

/**
 * GetSettings loads settings as a map "game.key" -> value.
 */
export function GetSettings(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(1419253203);
}

export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(2937747050);
}

/**
 * ResetData wipes user data (workspaces, mods, installs, runs) but keeps games and app_settings.
 */
export function ResetData(): $CancellablePromise<void> {
    return $Call.ByID(2171932109);
}

/**
 * SaveMergePreset saves a merge preset by name.
 */
export function SaveMergePreset(name: string, options: $models.MergerOptions): $CancellablePromise<void> {
    return $Call.ByID(3311953510, name, options);
}

/**
 * SaveSettings writes user settings to app_settings table.
 */
export function SaveSettings(settings: { [_ in string]?: string } | null): $CancellablePromise<void> {
    return $Call.ByID(3145424170, settings);
}
