// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ViewsService exposes non-IDE session views over Wails.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as views$0 from "./internal/views/models.js";

/**
 * GetEventDetail returns inspector content for one event id.
 */
export function GetEventDetail(workspaceID: string, eventID: string): $CancellablePromise<views$0.EventDetail | null> {
    return $Call.ByID(1284855892, workspaceID, eventID);
}

/**
 * GetEventGraph returns the defs-first event graph (no coordinates).
 */
export function GetEventGraph(workspaceID: string, params: views$0.EventGraphParams): $CancellablePromise<views$0.EventGraph> {
    return $Call.ByID(149081607, workspaceID, params);
}

/**
 * GetHealth returns grouped compatibility and loc rows for Workspace Health.
 */
export function GetHealth(workspaceID: string, order: string[] | null): $CancellablePromise<views$0.HealthReport> {
    return $Call.ByID(1332524529, workspaceID, order);
}

/**
 * LookupLoc returns the english loc text and site for key.
 */
export function LookupLoc(workspaceID: string, key: string): $CancellablePromise<views$0.LocLookup | null> {
    return $Call.ByID(2826275895, workspaceID, key);
}
