// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ViewsService exposes non-IDE session views over Wails.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as views$0 from "./internal/views/models.js";

/**
 * GetEventDetail returns inspector content for one event id.
 */
export function GetEventDetail(workspaceID: string, eventID: string): $CancellablePromise<views$0.EventDetail | null> {
    return $Call.ByID(1284855892, workspaceID, eventID);
}

/**
 * GetEventGraph returns the defs-first event graph (no coordinates).
 */
export function GetEventGraph(workspaceID: string, params: views$0.EventGraphParams): $CancellablePromise<views$0.EventGraph> {
    return $Call.ByID(149081607, workspaceID, params);
}

/**
 * GetLocCoverage returns per-language localization health for workspace mods.
 */
export function GetLocCoverage(workspaceID: string): $CancellablePromise<views$0.LocCoverage[] | null> {
    return $Call.ByID(475981069, workspaceID);
}

/**
 * GetOverrides returns FIOS/LIOS override rows for the conflict monitor.
 */
export function GetOverrides(workspaceID: string): $CancellablePromise<views$0.OverrideRow[] | null> {
    return $Call.ByID(1502410668, workspaceID);
}

/**
 * LookupLoc returns the english loc text and site for key.
 */
export function LookupLoc(workspaceID: string, key: string): $CancellablePromise<views$0.LocLookup | null> {
    return $Call.ByID(2826275895, workspaceID, key);
}
