// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WikiService exposes wiki sidecars over Wails. Scan still refreshes in-process.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wiki$0 from "./internal/wiki/models.js";

/**
 * Guide returns Guide pane pages for the active file. Locate fail → empty, not an error.
 */
export function Guide(workspaceID: string, path: string): $CancellablePromise<wiki$0.Guide | null> {
    return $Call.ByID(941746565, workspaceID, path);
}

/**
 * ModAffected is the Impact Check heuristic against harvest + wiki Modding bullets.
 */
export function ModAffected(workspaceID: string, modID: string, $from: string, to: string): $CancellablePromise<wiki$0.AffectedReport | null> {
    return $Call.ByID(3135124153, workspaceID, modID, $from, to);
}

/**
 * PatchPage returns one patch notes body by title or version label.
 */
export function PatchPage(gameID: string, version: string): $CancellablePromise<wiki$0.PatchPage | null> {
    return $Call.ByID(2002999296, gameID, version);
}

/**
 * Patches returns the Patch Notes version list, newest first.
 */
export function Patches(gameID: string): $CancellablePromise<wiki$0.PatchList | null> {
    return $Call.ByID(681892155, gameID);
}

/**
 * Status returns sidecar presence and counts for a game.
 */
export function Status(gameID: string): $CancellablePromise<wiki$0.Status | null> {
    return $Call.ByID(3464137233, gameID);
}
