// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WikiService fetches patch information from Paradox MediaWiki APIs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as repos$0 from "./internal/repos/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetPatchModdingSection fetches a patch page and caches full HTML plus the Modding section.
 */
export function GetPatchModdingSection(gameID: string, version: string): $CancellablePromise<repos$0.WikiPatch | null> {
    return $Call.ByID(3794037054, gameID, version);
}

/**
 * ListCachedPatches returns all cached patches for a game.
 */
export function ListCachedPatches(gameID: string): $CancellablePromise<repos$0.WikiPatch[] | null> {
    return $Call.ByID(146516213, gameID);
}

/**
 * ListVersions fetches the patch list from /Patches wiki page and returns versions.
 */
export function ListVersions(gameID: string): $CancellablePromise<$models.PatchVersion[] | null> {
    return $Call.ByID(35660038, gameID);
}
