// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkspaceService manages workspaces, game installs, and mods.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as game$0 from "./internal/game/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddGameInstall adds a new game installation. version empty → detected or latest.
 */
export function AddGameInstall(gameID: string, name: string, path: string, version: string): $CancellablePromise<$models.GameInstall | null> {
    return $Call.ByID(1554142306, gameID, name, path, version);
}

/**
 * AddWorkspaceMod adds a mod to a workspace.
 */
export function AddWorkspaceMod(workspaceID: string, name: string, path: string, tags: string[] | null, thumbnail: string): $CancellablePromise<$models.WorkspaceMod | null> {
    return $Call.ByID(123649806, workspaceID, name, path, tags, thumbnail);
}

/**
 * CountWorkspacesUsingInstall returns names of workspaces on this install.
 */
export function CountWorkspacesUsingInstall(installID: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1820687512, installID);
}

/**
 * CreateMod writes a new mod skeleton under parentDir and returns its path.
 */
export function CreateMod(gameID: string, parentDir: string, name: string, locLang: string, supportedVersion: string, description: string, thumbnailSrc: string): $CancellablePromise<string> {
    return $Call.ByID(3614381098, gameID, parentDir, name, locLang, supportedVersion, description, thumbnailSrc);
}

/**
 * CreateWorkspace creates a new workspace and default staging dir.
 */
export function CreateWorkspace(gameID: string, name: string, installID: string, tags: string[] | null): $CancellablePromise<$models.Workspace | null> {
    return $Call.ByID(2742011767, gameID, name, installID, tags);
}

/**
 * DefaultModParent is Documents/Paradox Interactive/<game>/mod, or "".
 */
export function DefaultModParent(gameID: string): $CancellablePromise<string> {
    return $Call.ByID(1639189285, gameID);
}

/**
 * DeleteGameInstall removes an install if no workspace uses it.
 */
export function DeleteGameInstall(id: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3448659062, id);
}

/**
 * DeleteWorkspace removes a workspace from PMT. Mod folders on disk stay.
 */
export function DeleteWorkspace(id: string): $CancellablePromise<void> {
    return $Call.ByID(1615435582, id);
}

/**
 * DetectGameVersion reads version from launcher-settings.json.
 */
export function DetectGameVersion(path: string): $CancellablePromise<string> {
    return $Call.ByID(4095463977, path);
}

/**
 * EnsureStagingDir creates the staging directory if it doesn't exist.
 */
export function EnsureStagingDir(workspaceID: string): $CancellablePromise<string> {
    return $Call.ByID(1205241180, workspaceID);
}

/**
 * FindGameInstalls returns Steam-detected installs for a game.
 */
export function FindGameInstalls(gameID: string): $CancellablePromise<game$0.DetectedInstall[] | null> {
    return $Call.ByID(1679875735, gameID);
}

/**
 * GetIdeRoots returns game / mod / staging folders for the workspace IDE.
 */
export function GetIdeRoots(workspaceID: string): $CancellablePromise<$models.IdeRoot[] | null> {
    return $Call.ByID(720395743, workspaceID);
}

/**
 * GetInstallCacheInfo returns scannedAt for the install's VanillaCache, or empty.
 */
export function GetInstallCacheInfo(installID: string): $CancellablePromise<$models.InstallCacheInfo | null> {
    return $Call.ByID(1009986005, installID);
}

/**
 * GetWorkspace returns a workspace by ID.
 */
export function GetWorkspace(id: string): $CancellablePromise<$models.Workspace | null> {
    return $Call.ByID(2164363903, id);
}

/**
 * ListGameInstalls returns all installs for a game.
 */
export function ListGameInstalls(gameID: string): $CancellablePromise<$models.GameInstall[] | null> {
    return $Call.ByID(3468235284, gameID);
}

/**
 * ListGames returns the supported-game table and vanilla origin token.
 */
export function ListGames(): $CancellablePromise<game$0.GameList> {
    return $Call.ByID(1635414117);
}

/**
 * ListWorkspaceMods returns all mods for a workspace, sorted by SortOrder then Name.
 */
export function ListWorkspaceMods(workspaceID: string): $CancellablePromise<$models.WorkspaceMod[] | null> {
    return $Call.ByID(1179220170, workspaceID);
}

/**
 * ListWorkspaces returns workspaces, optionally filtered by game. Pass "" for all.
 */
export function ListWorkspaces(gameID: string): $CancellablePromise<$models.Workspace[] | null> {
    return $Call.ByID(1786820820, gameID);
}

/**
 * MarkBrokenPaths checks all installs and mods, marks missing paths as broken.
 */
export function MarkBrokenPaths(): $CancellablePromise<void> {
    return $Call.ByID(2434148990);
}

/**
 * RemoveWorkspaceMod detaches a mod from a workspace.
 */
export function RemoveWorkspaceMod(workspaceID: string, modID: string): $CancellablePromise<void> {
    return $Call.ByID(1041246117, workspaceID, modID);
}

/**
 * ReorderWorkspaceMods writes SortOrder from the given id list.
 */
export function ReorderWorkspaceMods(workspaceID: string, modIDs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(3662824479, workspaceID, modIDs);
}

/**
 * SaveIdeSession stores open editor paths for a workspace.
 */
export function SaveIdeSession(workspaceID: string, files: string[] | null, active: string): $CancellablePromise<void> {
    return $Call.ByID(3665330071, workspaceID, files, active);
}

/**
 * SetInstallVersion pins the cache-key version (user override; empty → latest).
 */
export function SetInstallVersion(id: string, version: string): $CancellablePromise<void> {
    return $Call.ByID(2135672107, id, version);
}

/**
 * SetWorkspaceLocLang sets default loc language and loc-harvests if a session is live.
 */
export function SetWorkspaceLocLang(id: string, lang: string): $CancellablePromise<void> {
    return $Call.ByID(3609504639, id, lang);
}

/**
 * UpdateGameInstall updates path and docs_path, then refreshes version.
 */
export function UpdateGameInstall(id: string, path: string, docsPath: string): $CancellablePromise<$models.GameInstall | null> {
    return $Call.ByID(1401884060, id, path, docsPath);
}

/**
 * UpdateWorkspace updates workspace fields.
 */
export function UpdateWorkspace(id: string, name: string, installID: string, stagingDir: string, tags: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2311242704, id, name, installID, stagingDir, tags);
}

/**
 * UpdateWorkspaceMod updates a mod's name, tags, and optional color override.
 */
export function UpdateWorkspaceMod(workspaceID: string, modID: string, name: string, tags: string[] | null, color: string, thumbnail: string): $CancellablePromise<void> {
    return $Call.ByID(439726452, workspaceID, modID, name, tags, color, thumbnail);
}

/**
 * UpdateWorkspacePrefs sets IDE persist, default landing page, and origin colors.
 */
export function UpdateWorkspacePrefs(workspaceID: string, resetIdeOnOpen: boolean, defaultTool: string, gameColor: string, stagingColor: string): $CancellablePromise<void> {
    return $Call.ByID(3501301930, workspaceID, resetIdeOnOpen, defaultTool, gameColor, stagingColor);
}
