// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkspaceService manages workspaces, game installs, and mods.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as game$0 from "./internal/game/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as repos$0 from "./internal/repos/models.js";

/**
 * AddGameInstall adds a new game installation record. Detects version if possible.
 */
export function AddGameInstall(gameID: string, name: string, path: string): $CancellablePromise<repos$0.GameInstall | null> {
    return $Call.ByID(1554142306, gameID, name, path);
}

/**
 * AddWorkspaceMod adds a mod to a workspace.
 */
export function AddWorkspaceMod(workspaceID: string, name: string, path: string): $CancellablePromise<repos$0.WorkspaceMod | null> {
    return $Call.ByID(123649806, workspaceID, name, path);
}

/**
 * CreateWorkspace creates a new workspace. Sets default staging dir if not provided.
 */
export function CreateWorkspace(gameID: string, name: string, installID: string, tagsJSON: string, thumbnailPath: string): $CancellablePromise<repos$0.Workspace | null> {
    return $Call.ByID(2742011767, gameID, name, installID, tagsJSON, thumbnailPath);
}

/**
 * DefaultStagingDir returns the default staging directory path for a workspace.
 */
export function DefaultStagingDir(workspaceID: string): $CancellablePromise<string> {
    return $Call.ByID(3731287923, workspaceID);
}

/**
 * DeleteWorkspace removes a workspace and cascades deletes to mods and runs.
 */
export function DeleteWorkspace(id: string): $CancellablePromise<void> {
    return $Call.ByID(1615435582, id);
}

/**
 * DetectGameVersion attempts to read version from launcher-settings.json.
 */
export function DetectGameVersion(path: string): $CancellablePromise<string> {
    return $Call.ByID(4095463977, path);
}

/**
 * DetectModRoot reports whether path is a valid mod root for gameID.
 */
export function DetectModRoot(gameID: string, path: string): $CancellablePromise<boolean> {
    return $Call.ByID(850337951, gameID, path);
}

/**
 * EnsureStagingDir creates the staging directory if it doesn't exist.
 * When staging_dir is empty, assigns the default path and persists it.
 */
export function EnsureStagingDir(workspaceID: string): $CancellablePromise<string> {
    return $Call.ByID(1205241180, workspaceID);
}

/**
 * FindGameInstalls returns Steam-detected installs for a game.
 */
export function FindGameInstalls(gameID: string): $CancellablePromise<game$0.DetectedInstall[] | null> {
    return $Call.ByID(1679875735, gameID);
}

/**
 * GetScriptRoot returns the script root path for a game install.
 */
export function GetScriptRoot(installID: string): $CancellablePromise<string> {
    return $Call.ByID(4012809053, installID);
}

/**
 * GetWorkspace returns a workspace by ID.
 */
export function GetWorkspace(id: string): $CancellablePromise<repos$0.Workspace | null> {
    return $Call.ByID(2164363903, id);
}

/**
 * ListGameInstalls returns all installs for a game.
 */
export function ListGameInstalls(gameID: string): $CancellablePromise<repos$0.GameInstall[] | null> {
    return $Call.ByID(3468235284, gameID);
}

/**
 * ListGames returns supported games from the Go registry.
 */
export function ListGames(): $CancellablePromise<repos$0.Game[] | null> {
    return $Call.ByID(1635414117);
}

/**
 * ListWorkspaceMods returns all mods for a workspace.
 */
export function ListWorkspaceMods(workspaceID: string): $CancellablePromise<repos$0.WorkspaceMod[] | null> {
    return $Call.ByID(1179220170, workspaceID);
}

/**
 * ListWorkspaces returns workspaces, optionally filtered by game. Pass "" for all.
 */
export function ListWorkspaces(gameID: string): $CancellablePromise<repos$0.Workspace[] | null> {
    return $Call.ByID(1786820820, gameID);
}

/**
 * MarkBrokenPaths checks all installs and mods, marks missing paths as broken.
 */
export function MarkBrokenPaths(): $CancellablePromise<void> {
    return $Call.ByID(2434148990);
}

/**
 * RemoveWorkspaceMod deletes a mod from a workspace.
 */
export function RemoveWorkspaceMod(modID: string): $CancellablePromise<void> {
    return $Call.ByID(1041246117, modID);
}

/**
 * SetActiveWorkspace sets a workspace as active (clears others for that game).
 */
export function SetActiveWorkspace(workspaceID: string): $CancellablePromise<void> {
    return $Call.ByID(1281878305, workspaceID);
}

/**
 * UpdateGameInstall updates path and docs_path, then refreshes version.
 */
export function UpdateGameInstall(id: string, path: string, docsPath: string): $CancellablePromise<repos$0.GameInstall | null> {
    return $Call.ByID(1401884060, id, path, docsPath);
}

/**
 * UpdateWorkspace updates workspace fields.
 */
export function UpdateWorkspace(id: string, name: string, installID: string, stagingDir: string, tagsJSON: string, thumbnailPath: string): $CancellablePromise<void> {
    return $Call.ByID(2311242704, id, name, installID, stagingDir, tagsJSON, thumbnailPath);
}
