// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Status reports whether a cached model exists.
 */
export interface Status {
    "present": boolean;
    "workspaceId": string;
    "builtAt"?: string;
    "defCount": number;
    "edgeCount": number;
    "path"?: string;
}
