// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Dependencies is the inspector payload for one definition.
 */
export interface Dependencies {
    "def": DependencyDef | null;
    "dependents": DependencyGroup[] | null;
    "dependencies": DependencyGroup[] | null;
}

/**
 * DependencyDef is the resolved subject of a dependency query.
 */
export interface DependencyDef {
    "name": string;
    "kind": string;
    "file": string;
    "line": number;
}

/**
 * DependencyGroup is dependents or dependencies of one kind.
 */
export interface DependencyGroup {
    "kind": string;
    "items": DependencyItem[] | null;
}

/**
 * DependencyItem is one named site in a dependency group.
 */
export interface DependencyItem {
    "name": string;
    "file": string;
    "line": number;
}

/**
 * EventDetail is the inspector payload for one event.
 */
export interface EventDetail {
    "id": string;
    "file": string;
    "rel"?: string;
    "origin"?: string;
    "line": number;
    "endLine": number;
    "fields": EventFieldInfo[] | null;
    "type"?: string;
    "hidden"?: boolean;
    "theme"?: string;
    "title"?: EventLocField | null;
    "desc"?: EventLocField | null;
    "flavor"?: EventLocField | null;
    "sections": EventSectionInfo[] | null;
    "options": EventOptionInfo[] | null;
    "refs": EventRefInfo[] | null;
}

/**
 * EventFieldInfo is a top-level scalar in an event or option body.
 */
export interface EventFieldInfo {
    "key": string;
    "value": string;
    "line": number;
    "quoted"?: boolean;
}

/**
 * EventGateInfo is a rendered trigger or ai_chance block.
 */
export interface EventGateInfo {
    "line": number;
    "lines": EventScriptLine[] | null;
    "totalLines": number;
}

/**
 * EventGraph is a coordinate-free node/edge payload for frontend layout.
 */
export interface EventGraph {
    "nodes": EventGraphNode[] | null;
    "edges": EventGraphEdge[] | null;
    "truncated": boolean;
    "suggestions": EventGraphSuggestions;
    "emptyReason"?: string;
}

/**
 * EventGraphEdge is a directed link. Via names the referencing field or hop chain.
 */
export interface EventGraphEdge {
    "from": string;
    "to": string;
    "via": string;
    "label"?: string;
    "phase"?: string;
    "fromLine"?: number | null;
    "delay"?: string;
    "weight"?: number | null;
}

/**
 * EventGraphNode is one graph card. There is no x/y: layout is frontend/dagre.
 */
export interface EventGraphNode {
    "id": string;
    "kind": string;
    "source": string;
    "file"?: string;
    "line"?: number;
    "title"?: string;
    "theme"?: string;
    "options"?: number;
    "triggerSummary"?: string;
    "fires"?: number;
    "steps"?: EventGraphStep[] | null;
}

/**
 * EventGraphParams selects which definitions to draw.
 */
export interface EventGraphParams {
    "root"?: string;
    "namespace"?: string;
    "modRoot"?: string;
    "maxNodes"?: number;
    "themes"?: boolean;
}

/**
 * EventGraphStep is one card row in execution order.
 */
export interface EventGraphStep {
    "phase": string;
    "index"?: number | null;
    "text"?: string;
    "line": number;
}

/**
 * EventGraphSuggestions is the catalog for root and namespace pickers.
 */
export interface EventGraphSuggestions {
    "ids": SuggestionItem[] | null;
    "namespaces": SuggestionItem[] | null;
}

/**
 * EventLocField is a resolved localization key.
 */
export interface EventLocField {
    "key": string;
    "text"?: string;
    "file"?: string;
    "line"?: number;
    "dynamic"?: boolean;
}

/**
 * EventOptionInfo is one option = { } block.
 */
export interface EventOptionInfo {
    "line": number;
    "fields": EventFieldInfo[] | null;
    "name"?: EventLocField | null;
    "effectKeys": string[] | null;
    "hasTrigger": boolean;
    "hasAiChance": boolean;
    "trigger"?: EventGateInfo | null;
    "aiChance"?: EventGateInfo | null;
    "lines": EventScriptLine[] | null;
    "totalLines": number;
    "targets": EventStepTarget[] | null;
    "targetsTotal": number;
}

/**
 * EventRefInfo is a named reference inside an event body.
 */
export interface EventRefInfo {
    "name": string;
    "kind": string;
    "line": number;
    "defFile"?: string;
    "defLine"?: number;
    "defCount"?: number;
}

/**
 * EventScriptLine is one rendered pseudo-script line.
 */
export interface EventScriptLine {
    "depth": number;
    "text": string;
    "line": number;
}

/**
 * EventSectionInfo is one named event block (trigger, immediate, …).
 */
export interface EventSectionInfo {
    "name": string;
    "line": number;
    "keys": string[] | null;
    "lines": EventScriptLine[] | null;
    "totalLines": number;
    "targets": EventStepTarget[] | null;
    "targetsTotal": number;
}

/**
 * EventStepTarget is an event/on_action a block hands control to.
 */
export interface EventStepTarget {
    "via": string;
    "name": string;
    "kind": string;
    "line": number;
    "file"?: string;
    "defLine"?: number;
    "defCount"?: number;
    "fires"?: EventStepTarget[] | null;
    "firesTotal"?: number;
}

/**
 * LocCoverage is per-language localization health for the workspace mods.
 */
export interface LocCoverage {
    "language": string;
    "defined": number;
    "missing": LocIssue[] | null;
    "orphaned": LocIssue[] | null;
    "untranslated": LocIssue[] | null;
}

/**
 * LocIssue is one coverage finding.
 */
export interface LocIssue {
    "key": string;
    "file"?: string;
    "rel"?: string;
    "line"?: number;
    "value"?: string;
    "origin"?: string;
}

/**
 * LocLookup is one localization key's resolved english text and site.
 */
export interface LocLookup {
    "key": string;
    "text": string;
    "file"?: string;
    "rel"?: string;
    "line"?: number;
    "origin"?: string;
}

/**
 * SuggestionItem is one picker entry. Origin is "" for vanilla, else a mod id.
 */
export interface SuggestionItem {
    "id": string;
    "origin": string;
}
