// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type {
    CodeAction,
    CompletionItem,
    Diagnostic,
    FoldingRange,
    HoverResult,
    InlayHint,
    Location,
    Position,
    Range,
    SemanticSpan,
    SignatureHelp,
    SymbolInformation,
    TextEdit,
    WorkspaceEdit
} from "./models.js";
