// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CodeAction is a quick-fix.
 */
export interface CodeAction {
    "title": string;
    "kind"?: string;
    "edit"?: WorkspaceEdit | null;
}

/**
 * CompletionItem is one completion suggestion. Kind uses LSP CompletionItemKind.
 */
export interface CompletionItem {
    "label": string;
    "kind"?: number;
    "detail"?: string;
}

/**
 * Diagnostic is a parse or semantic issue for a file.
 */
export interface Diagnostic {
    "range": Range;

    /**
     * 1 error, 2 warning
     */
    "severity": number;
    "message": string;
    "source"?: string;
    "code"?: string;
}

/**
 * FoldingRange is a foldable line span (0-based, inclusive).
 */
export interface FoldingRange {
    "startLine": number;
    "endLine": number;
}

/**
 * HoverResult is hover card text. Origin/rel/line/rootPath describe the def site.
 */
export interface HoverResult {
    "contents": string;
    "range"?: Range | null;
    "origin"?: string;
    "rel"?: string;
    "line"?: number;
    "rootPath"?: string;
}

/**
 * Location points at a definition or reference.
 */
export interface Location {
    "uri": string;
    "range": Range;
}

/**
 * Position is a 0-based line and UTF-8 byte column.
 */
export interface Position {
    "line": number;
    "character": number;
}

/**
 * Range is a half-open LSP-style span in UTF-8 byte columns.
 */
export interface Range {
    "start": Position;
    "end": Position;
}

/**
 * SignatureHelp is a call-signature tooltip.
 */
export interface SignatureHelp {
    "label": string;
    "documentation"?: string;
}

/**
 * SymbolInformation describes a document or workspace symbol.
 */
export interface SymbolInformation {
    "name": string;
    "kind": number;
    "location": Location;
    "containerName"?: string;
}

/**
 * TextEdit is an LSP-style replacement.
 */
export interface TextEdit {
    "range": Range;
    "newText": string;
}

/**
 * WorkspaceEdit maps document URIs (absolute paths) to edits. Create lists
 * files that should be created before the edits are applied.
 */
export interface WorkspaceEdit {
    "changes": { [_ in string]?: TextEdit[] | null } | null;
    "create"?: string[] | null;
}
