// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CompletionItem is a single completion suggestion.
 */
export interface CompletionItem {
    "label": string;
    "kind"?: number;
    "detail"?: string;
}

/**
 * Diagnostic is a parse/semantic issue for a file.
 */
export interface Diagnostic {
    "range": Range;

    /**
     * 1=error 2=warning
     */
    "severity": number;
    "message": string;
    "source"?: string;
}

/**
 * HoverResult is markdown/plain hover text.
 */
export interface HoverResult {
    "contents": string;
    "range"?: Range | null;
}

/**
 * Location points at a definition or reference.
 */
export interface Location {
    "uri": string;
    "range": Range;
}

/**
 * Position is a 0-based line/character offset (LSP style).
 */
export interface Position {
    "line": number;
    "character": number;
}

/**
 * Range is an LSP-style text range.
 */
export interface Range {
    "start": Position;
    "end": Position;
}

/**
 * SymbolInformation describes a document or workspace symbol.
 */
export interface SymbolInformation {
    "name": string;
    "kind": number;
    "location": Location;
    "containerName"?: string;
}
