// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Schema defines how to identify a type of script object.
 */
export interface Schema {
    "name": string;
    "paths": string[] | null;
    "keyPattern": string;
    "keyPrefixes"?: string[] | null;
    "keySuffixes"?: string[] | null;
    "attributes"?: string[] | null;
    "inlineKeyPattern"?: string;
    "inlineKeyKeywords"?: string[] | null;
}
