# Hugo site for https://idodavis.github.io/paradox-modding-tools/
baseURL = "https://idodavis.github.io/paradox-modding-tools/"
languageCode = "en-us"
title = "Paradox Modding Tools"
disableKinds = ["taxonomy", "term", "RSS", "sitemap"]
enableRobotsTXT = true
relativeURLs = false

[params]
  github = "https://github.com/idodavis/paradox-modding-tools"
  releases = "https://github.com/idodavis/paradox-modding-tools/releases"
  editBase = "https://github.com/idodavis/paradox-modding-tools/edit/master/docs/content"

[outputs]
  home = ["HTML", "JSON"]

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  style = "onedark"
  noClasses = false
  lineNos = false

[markup.tableOfContents]
  startLevel = 2
  endLevel = 3
