// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EventDetail is the inspector payload for one event.
 */
export interface EventDetail {
    "id": string;
    "file": string;
    "rel"?: string;
    "origin"?: string;
    "line": number;
    "fields": EventFieldInfo[] | null;
    "type"?: string;
    "hidden"?: boolean;
    "theme"?: string;
    "title"?: EventLocField | null;
    "desc"?: EventLocField | null;
    "flavor"?: EventLocField | null;
    "sections": EventSectionInfo[] | null;
    "options": EventOptionInfo[] | null;
    "refGroups"?: RefKindGroup[] | null;
    "incoming"?: EventGraphEdge[] | null;
}

/**
 * EventFieldInfo is a top-level scalar in an event or option body.
 */
export interface EventFieldInfo {
    "key": string;
    "value": string;
    "line": number;
    "quoted"?: boolean;
}

/**
 * EventGraph is a coordinate-free node/edge payload for frontend layout.
 */
export interface EventGraph {
    "nodes": EventGraphNode[] | null;
    "edges": EventGraphEdge[] | null;
    "truncated": boolean;
    "suggestions": EventGraphSuggestions;
    "emptyReason"?: string;
}

/**
 * EventGraphEdge is a directed link. Via names the referencing field or hop chain.
 */
export interface EventGraphEdge {
    "from": string;
    "to": string;
    "via": string;
    "label"?: string;
    "kind"?: string;
}

/**
 * EventGraphNode is one graph card. There is no x/y: layout is frontend/dagre.
 */
export interface EventGraphNode {
    "id": string;
    "kind": string;
    "origin"?: string;
    "originName"?: string;
    "title"?: string;
    "role"?: string;
    "fires"?: number;
}

/**
 * EventGraphParams selects which definitions to draw.
 */
export interface EventGraphParams {
    "root"?: string;
    "namespace"?: string;
    "origins"?: string[] | null;
    "maxNodes"?: number;
    "expand"?: string[] | null;
}

/**
 * EventGraphSuggestions is the catalog for root and namespace pickers.
 */
export interface EventGraphSuggestions {
    "ids": SuggestionItem[] | null;
    "namespaces": SuggestionItem[] | null;
}

/**
 * EventLocField is a resolved localization key.
 */
export interface EventLocField {
    "key": string;
    "text"?: string;
    "file"?: string;
    "line"?: number;
}

/**
 * EventOptionInfo is one option = { } block.
 */
export interface EventOptionInfo {
    "fields": EventFieldInfo[] | null;
    "name"?: EventLocField | null;
    "trigger"?: EventSectionInfo | null;
    "aiChance"?: EventSectionInfo | null;
    "lines": EventScriptLine[] | null;
    "targets": EventStepTarget[] | null;
}

/**
 * EventRefInfo is a named reference inside an event body.
 */
export interface EventRefInfo {
    "name": string;
    "kind": string;
    "line": number;
    "defFile"?: string;
    "defLine"?: number;
}

/**
 * EventScriptLine is one rendered pseudo-script line.
 */
export interface EventScriptLine {
    "depth": number;
    "text": string;
}

/**
 * EventSectionInfo is one named script block (trigger, immediate, option gate, …).
 */
export interface EventSectionInfo {
    "name": string;
    "role"?: string;
    "lines": EventScriptLine[] | null;
    "targets": EventStepTarget[] | null;
}

/**
 * EventStepTarget is an event/on_action a block hands control to.
 */
export interface EventStepTarget {
    "name": string;
}

/**
 * LocCoverage is per-language localization health for the workspace mods.
 */
export interface LocCoverage {
    "language": string;
    "defined": number;
    "issues": LocIssueRow[] | null;
}

/**
 * LocIssueRow is one flat coverage finding for the table and overview tree.
 */
export interface LocIssueRow {
    "language": string;
    "kind": string;
    "key": string;
    "file"?: string;
    "rel"?: string;
    "line"?: number;
    "value"?: string;
    "origin"?: string;
    "originName"?: string;
}

/**
 * LocLookup is one localization key's resolved english text and site.
 */
export interface LocLookup {
    "key": string;
    "text": string;
    "file"?: string;
    "line"?: number;
    "origin"?: string;
    "originName"?: string;
}

/**
 * OverrideRow is one contested (kind, key): resolution rule, winning origin, and
 * every site that defines it. Overlay is true when exactly one mod shadows vanilla.
 */
export interface OverrideRow {
    "kind": string;
    "name": string;
    "rule": string;
    "winner": string;
    "winnerName"?: string;
    "sites": OverrideSite[] | null;
    "overlay"?: boolean;
}

/**
 * OverrideSite is one place a key is defined, for the conflict monitor.
 */
export interface OverrideSite {
    "origin": string;
    "originName"?: string;
    "file": string;
    "line": number;
}

/**
 * RefKindGroup groups refs by kind for the inspector accordion.
 */
export interface RefKindGroup {
    "kind": string;
    "refs": EventRefInfo[] | null;
}

/**
 * SuggestionItem is one picker entry. Origin is "" for vanilla, else a mod id.
 */
export interface SuggestionItem {
    "id": string;
    "origin": string;
}
